// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  NEXTJS_ENV: string;
  HONO_APP: Service<DataFetcher>;
  ASSETS: Fetcher;
}
