import type { DataFetcher } from "@workers-binding-playground/hono";
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

declare global {
  interface CloudflareEnv {
    NEXTJS_ENV: string;
    HONO_APP: Service<DataFetcher>;
    PRIVATE_API: Fetcher;
    ASSETS: Fetcher;
  }
}
