packages:
  - apps/**
catalog:
  "@biomejs/biome": ^1.9.4
  "@cloudflare/workers-types": ^4.20250214.0
  "@opennextjs/cloudflare": ^0.5.8
  "@types/node": ^20
  "@types/react": ^18
  "@types/react-dom": ^18
  hono: ^4.7.4
  next: 14.2.24
  postcss: ^8
  react: ^18
  react-dom: ^18
  tailwindcss: ^3.4.1
  turbo: ^2.4.2
  typescript: ^5
  wrangler: ^3.109.2
